"""Initial schema — all 10 tables + RLS policies + indexes.

Revision: 001
Created: 2026-08-26

Hand-written (not autogenerated) for production correctness.
Every table follows the multi-tenant pattern: org_id column + RLS policy.

RLS policy pattern (applied to every tenant-scoped table):
  - Row is readable/writable only when org_id = current_setting('app.current_org_id')
  - The application sets this via `SET LOCAL app.current_org_id = '<uuid>'` before
    executing queries — see app/db/session.py for the implementation.
  - Defence-in-depth: the API layer ALSO filters by org_id in every query.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM, JSON, UUID

# revision identifiers used by Alembic
revision: str = "001"
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── Extensions ─────────────────────────────────────────────────────────────
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ── Enums ──────────────────────────────────────────────────────────────────
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE user_role_enum AS ENUM ('admin', 'recruiter');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE document_type_enum AS ENUM ('original', 'generated');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE review_action_enum AS ENUM ('confirm', 'edit', 'remove');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    # ─────────────────────────────────────────────────────────────────────────
    # organizations
    # ─────────────────────────────────────────────────────────────────────────
    op.create_table(
        "organizations",
        sa.Column("id", UUID(as_uuid=False), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("plan_tier", sa.String(50), nullable=False, server_default="internal"),
        sa.Column("branding_config", JSON, nullable=False, server_default="{}"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )

    # ─────────────────────────────────────────────────────────────────────────
    # users
    # ─────────────────────────────────────────────────────────────────────────
    op.create_table(
        "users",
        sa.Column("id", UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "org_id",
            UUID(as_uuid=False),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=True),
        sa.Column("google_sub", sa.String(255), nullable=True),
        sa.Column(
            "role",
            PG_ENUM("admin", "recruiter", name="user_role_enum", create_type=False),
            nullable=False,
            server_default="recruiter",
        ),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.UniqueConstraint("org_id", "email", name="uq_users_org_email"),
    )
    op.create_index("ix_users_org_id", "users", ["org_id"])
    op.create_index("ix_users_email", "users", ["email"])

    # ─────────────────────────────────────────────────────────────────────────
    # candidates
    # ─────────────────────────────────────────────────────────────────────────
    op.create_table(
        "candidates",
        sa.Column("id", UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "org_id",
            UUID(as_uuid=False),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("master_profile_id", UUID(as_uuid=False), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.create_index("ix_candidates_org_id_created_at", "candidates", ["org_id", "created_at"])

    # ─────────────────────────────────────────────────────────────────────────
    # documents
    # ─────────────────────────────────────────────────────────────────────────
    op.create_table(
        "documents",
        sa.Column("id", UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "org_id",
            UUID(as_uuid=False),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "candidate_id",
            UUID(as_uuid=False),
            sa.ForeignKey("candidates.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "type",
            PG_ENUM("original", "generated", name="document_type_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("original_filename", sa.String(500), nullable=False),
        sa.Column("mime_type", sa.String(100), nullable=False),
        sa.Column("storage_url", sa.Text, nullable=False),
        sa.Column("file_size_bytes", sa.Integer, nullable=True),
        sa.Column("extraction_instructions", sa.Text, nullable=True),
        sa.Column("parse_status", sa.String(50), nullable=False, server_default="pending"),
        sa.Column("raw_text", sa.Text, nullable=True),
        sa.Column(
            "uploaded_by",
            UUID(as_uuid=False),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.create_index("ix_documents_org_id_candidate_id", "documents", ["org_id", "candidate_id"])
    op.create_index("ix_documents_org_id_created_at", "documents", ["org_id", "created_at"])

    # ─────────────────────────────────────────────────────────────────────────
    # candidate_profiles
    # ─────────────────────────────────────────────────────────────────────────
    op.create_table(
        "candidate_profiles",
        sa.Column("id", UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "org_id",
            UUID(as_uuid=False),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "candidate_id",
            UUID(as_uuid=False),
            sa.ForeignKey("candidates.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "source_document_id",
            UUID(as_uuid=False),
            sa.ForeignKey("documents.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("profile_json", JSON, nullable=False),
        sa.Column(
            "extraction_status", sa.String(50), nullable=False, server_default="pending"
        ),
        sa.Column("extraction_model", sa.String(100), nullable=True),
        sa.Column("extraction_version", sa.String(20), nullable=True),
        sa.Column("overall_confidence", sa.Numeric(4, 3), nullable=True),
        sa.Column(
            "reviewed_by",
            UUID(as_uuid=False),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.create_index(
        "ix_profiles_org_candidate", "candidate_profiles", ["org_id", "candidate_id"]
    )
    op.create_index(
        "ix_profiles_org_status",
        "candidate_profiles",
        ["org_id", "extraction_status"],
    )

    # ─────────────────────────────────────────────────────────────────────────
    # templates
    # ─────────────────────────────────────────────────────────────────────────
    op.create_table(
        "templates",
        sa.Column("id", UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "org_id",
            UUID(as_uuid=False),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("config_json", JSON, nullable=False, server_default="{}"),
        sa.Column("docx_storage_url", sa.Text, nullable=True),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column(
            "created_by",
            UUID(as_uuid=False),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.create_index("ix_templates_org_id_active", "templates", ["org_id", "is_active"])

    # ─────────────────────────────────────────────────────────────────────────
    # generations
    # ─────────────────────────────────────────────────────────────────────────
    op.create_table(
        "generations",
        sa.Column("id", UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "org_id",
            UUID(as_uuid=False),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "candidate_id",
            UUID(as_uuid=False),
            sa.ForeignKey("candidates.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "template_id",
            UUID(as_uuid=False),
            sa.ForeignKey("templates.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "profile_id",
            UUID(as_uuid=False),
            sa.ForeignKey("candidate_profiles.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("status", sa.String(50), nullable=False, server_default="pending"),
        sa.Column("formatting_instructions", sa.Text, nullable=True),
        sa.Column(
            "output_document_id",
            UUID(as_uuid=False),
            sa.ForeignKey("documents.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "triggered_by",
            UUID(as_uuid=False),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("error_message", sa.Text, nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.create_index("ix_generations_org_candidate", "generations", ["org_id", "candidate_id"])
    op.create_index("ix_generations_org_status", "generations", ["org_id", "status"])

    # ─────────────────────────────────────────────────────────────────────────
    # review_events
    # ─────────────────────────────────────────────────────────────────────────
    op.create_table(
        "review_events",
        sa.Column("id", UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "org_id",
            UUID(as_uuid=False),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "profile_id",
            UUID(as_uuid=False),
            sa.ForeignKey("candidate_profiles.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("field_path", sa.Text, nullable=False),
        sa.Column(
            "action",
            PG_ENUM("confirm", "edit", "remove", name="review_action_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("old_value", JSON, nullable=True),
        sa.Column("new_value", JSON, nullable=True),
        sa.Column(
            "user_id",
            UUID(as_uuid=False),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.create_index("ix_review_events_profile_id", "review_events", ["profile_id"])

    # ─────────────────────────────────────────────────────────────────────────
    # usage_events
    # ─────────────────────────────────────────────────────────────────────────
    op.create_table(
        "usage_events",
        sa.Column("id", UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "org_id",
            UUID(as_uuid=False),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(100), nullable=False),
        sa.Column("quantity", sa.Integer, nullable=False, server_default="1"),
        sa.Column("reference_id", UUID(as_uuid=False), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.create_index("ix_usage_events_org_id_created_at", "usage_events", ["org_id", "created_at"])

    # ─────────────────────────────────────────────────────────────────────────
    # api_keys
    # ─────────────────────────────────────────────────────────────────────────
    op.create_table(
        "api_keys",
        sa.Column("id", UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "org_id",
            UUID(as_uuid=False),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("key_hash", sa.String(64), nullable=False, unique=True),
        sa.Column("scopes", JSON, nullable=False, server_default="[]"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_by",
            UUID(as_uuid=False),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_api_keys_org_id", "api_keys", ["org_id"])

    # ─────────────────────────────────────────────────────────────────────────
    # Row-Level Security policies
    # Each table: only rows whose org_id matches the session variable are visible.
    # The application sets `SET LOCAL app.current_org_id = '<uuid>'` before queries.
    # See docs/integration-guide-phase-2-3.md for the worker pattern.
    # ─────────────────────────────────────────────────────────────────────────
    _rls_tables = [
        "users",
        "candidates",
        "documents",
        "candidate_profiles",
        "templates",
        "generations",
        "review_events",
        "usage_events",
        "api_keys",
    ]

    for table in _rls_tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (org_id::text = current_setting('app.current_org_id', true))
            WITH CHECK (org_id::text = current_setting('app.current_org_id', true))
            """
        )

    # Superuser bypass policy — allows the seed/migration user to operate without RLS
    # The app service role NEVER has superuser — it uses a restricted role.
    # organizations has no org_id column, so no RLS needed.


def downgrade() -> None:
    # Drop tables in reverse FK order
    tables = [
        "api_keys",
        "usage_events",
        "review_events",
        "generations",
        "candidate_profiles",
        "templates",
        "documents",
        "candidates",
        "users",
        "organizations",
    ]
    for t in tables:
        op.drop_table(t)

    op.execute("DROP TYPE IF EXISTS review_action_enum")
    op.execute("DROP TYPE IF EXISTS document_type_enum")
    op.execute("DROP TYPE IF EXISTS user_role_enum")
